name: Free2 Telegram Notifier


on:

  schedule:
    - cron: "*/45 * * * *"

  workflow_dispatch:



jobs:

  check-messages:


    runs-on: ubuntu-latest



    steps:


      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.x"



      - name: Install packages
        run: |
          pip install requests beautifulsoup4



      - name: Run checker

        env:

          GMAIL_USER: ${{ secrets.GMAIL_USER }}

          GMAIL_TO: ${{ secrets.GMAIL_TO }}

          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}


        run: |

          python checker.py
